### ISSUE TITLE
Does this support automated failover by changing role from slave to master?

### ISSUE THREAD

**Issue by savingschampion** [justindowning/puppet-wal_e#2]

**Comment by jdowning** [comment]
No, but a slave can be changed into the master as set by the `trigger_file` in `recovery.conf`. Using the defaults provided in this module, you would simply `touch /var/lib/postgresql/9.2/main/pg_failover_trigger` on the slave to failover.

**Comment by savingschampion** [comment]
ok, could you remove the hard coded 9.2 in that path?

**Comment by jdowning** [comment]
It's not hard coded. You can set it when you call `class { 'wal_e': }` as documented [here](https://github.com/justindowning/puppet-wal_e/blob/master/manifests/init.pp#L41).

**Comment by savingschampion** [comment]
Sorry I was getting an old copy of this module from forge. I also realised I was the one who stopped it from being hardcoded in the first place, with my pull request.
